# Generated by Django 4.0 on 2022-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='pincode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(),
        ),
    ]
