# Generated by Django 4.0 on 2022-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerdetails_address_customerdetails_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='accessToken',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='emailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
