# Generated by Django 4.0 on 2022-02-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanAdminDetails',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productShortDecription', models.CharField(max_length=500, unique=True)),
                ('productName', models.CharField(max_length=40, unique=True)),
                ('price', models.IntegerField()),
                ('totalTime', models.IntegerField()),
                ('productCompleteDescription', models.JSONField(null=True)),
                ('productCategory', models.CharField(max_length=20)),
            ],
        ),
    ]
