# Generated by Django 4.0 on 2022-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_handymanadmindetails_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productCompleteDescription',
            field=models.JSONField(default=''),
        ),
    ]
