# Generated by Django 4.0 on 2022-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdetails_productcompletedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productCompleteDescription',
            field=models.JSONField(),
        ),
    ]
