# Generated by Django 4.0 on 2022-02-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdetails_productcompletedescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='ProductId',
            new_name='productId',
        ),
    ]
