# Generated by Django 4.0 on 2022-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanAdminDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('mobileNumber', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('accessToken', models.CharField(max_length=500)),
                ('createdOn', models.DateField()),
            ],
        ),
    ]
