# Generated by Django 4.0 on 2022-01-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanadmindetails',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
