# Generated by Django 4.0 on 2022-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0004_rename_branchid_handymanadmindetails_branchid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='stateName',
            field=models.CharField(max_length=30),
        ),
    ]
