# Generated by Django 4.0 on 2022-01-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0006_alter_handymanadmindetails_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='branchId',
            field=models.IntegerField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='mobileNumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
