# Generated by Django 4.0 on 2022-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0007_alter_handymanadmindetails_branchid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='mobileNumber',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
