# Generated by Django 4.0 on 2022-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0008_alter_handymanadmindetails_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='branchId',
            field=models.IntegerField(max_length=3),
        ),
    ]
