# Generated by Django 4.0 on 2022-01-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0009_alter_handymanadmindetails_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='branchId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='mobileNumber',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='stateName',
            field=models.CharField(max_length=20),
        ),
    ]
