# Generated by Django 4.0 on 2022-01-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0010_alter_handymanadmindetails_branchid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanadmindetails',
            name='cityName',
            field=models.CharField(default='INDIA', max_length=20),
        ),
    ]
