# Generated by Django 4.0 on 2022-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0011_handymanadmindetails_cityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanadmindetails',
            name='cityName',
            field=models.CharField(max_length=20),
        ),
    ]
