# Generated by Django 4.0 on 2023-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymanadmin', '0012_alter_handymanadmindetails_cityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanadmindetails',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
