# Generated by Django 4.0 on 2021-12-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobileNumber', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=160)),
                ('isActivated', models.BooleanField(null=True)),
                ('accessToken', models.CharField(max_length=160)),
                ('createdOn', models.DateField()),
            ],
        ),
    ]
