# Generated by Django 4.0 on 2021-12-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(),
        ),
    ]
