# Generated by Django 4.0 on 2022-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_workerdetails_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='accessToken',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
