# Generated by Django 4.0 on 2022-01-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workerdetails',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workerdetails',
            name='pincode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workerdetails',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
