# Generated by Django 4.0 on 2022-01-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_workerdetails_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
