# Generated by Django 4.0 on 2022-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
