# Generated by Django 4.0 on 2022-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_alter_workerdetails_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(),
        ),
    ]
