# Generated by Django 4.0 on 2022-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_alter_workerdetails_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
