# Generated by Django 4.0 on 2022-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_alter_workerdetails_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='worktype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
