# Generated by Django 4.0 on 2022-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_remove_workerdetails_name_workerdetails_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='accessToken',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='createdOn',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
