# Generated by Django 4.0 on 2022-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0017_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='accessToken',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='createdOn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
