# Generated by Django 4.0 on 2022-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
    ]
