# Generated by Django 4.0 on 2022-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0019_alter_workerdetails_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
