# Generated by Django 4.0 on 2022-01-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0021_alter_workerdetails_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalDetails', models.JSONField()),
                ('familyDetails', models.JSONField()),
                ('residenceDetails', models.JSONField()),
                ('workDetails', models.JSONField()),
                ('kyc', models.JSONField()),
                ('bankDetails', models.JSONField()),
                ('foreignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workerdetails')),
            ],
        ),
    ]
