# Generated by Django 4.0 on 2022-01-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0023_alter_workerinformation_bankdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinformation',
            name='foreignId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workerdetails', unique=True),
        ),
    ]
