# Generated by Django 4.0 on 2022-01-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0024_alter_workerinformation_foreignid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='workerinformation',
            name='foreignId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='worker.workerdetails'),
        ),
    ]
