# Generated by Django 4.0 on 2022-01-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0025_remove_workerinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinformation',
            name='foreignId',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='worker.workerdetails'),
        ),
    ]
