# Generated by Django 4.0 on 2022-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0027_alter_workerinformation_foreignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinformation',
            name='key',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
