# Generated by Django 4.0 on 2022-01-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0028_workerinformation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerinformation',
            name='key',
        ),
    ]
