# Generated by Django 4.0 on 2022-01-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0036_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
