# Generated by Django 4.0 on 2022-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0039_alter_workerdetails_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='accessToken',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='mobileNumber',
            field=models.BigIntegerField(default=65465, unique=True),
            preserve_default=False,
        ),
    ]
