# Generated by Django 4.0 on 2022-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0040_alter_workerdetails_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='accessToken',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='worktype',
            field=models.CharField(max_length=30),
        ),
    ]
